[Feat] Predictor precision for TF and PT backend
mindee/doctr pull request #1204
Opened 2023-05-29 13:58 UTC by felixdittrich92

This PR:

- adds dtype to predictor / det predictor and reco predictor

Any feedback is welcome :hugs: 

tests depends on: #1201 
issue: #1112

2023-06-01 08:33 UTC, felixdittrich92 commented
@odulcy-mindee ready for review if tests done :)

2023-06-09 16:58 UTC, nikokks commented
for debugging...
when I do 
```
python3.8 references/classification/train_tensorflow.py vit_s -b 1 --val-samples 1 --train-samples 1 --epochs 1
```
it gets 
```
/home/nikkokks/.local/lib/python3.8/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
Namespace(amp=False, arch='vit_s', batch_size=1, epochs=1, export_onnx=False, find_lr=False, font='FreeMono.ttf,FreeSans.ttf,FreeSerif.ttf', input_size=32, lr=0.001, name=None, pretrained=False, push_to_hub=False, resume=None, show_samples=False, test_only=False, train_samples=1, val_samples=1, vocab='french', wb=False, workers=None)
Validation set loaded in 1.713s (126 samples in 126 batches)
Train set loaded in 1.712s (126 samples in 126 batches)
Validation loss decreased inf --> 5.27862: saving state...                                                                                                      
Epoch 1/1 - Validation loss: 5.27862 (Acc: 2.38%)
```
but when I run any mobilenet
```
python3.8 references/classification/train_tensorflow.py mobilenet_v3_large -b 1 --val-samples 1 --train-samples 1 --epochs 1 
```
it gets
```

/home/nikkokks/.local/lib/python3.8/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
Namespace(amp=False, arch='mobilenet_v3_large', batch_size=1, epochs=1, export_onnx=False, find_lr=False, font='FreeMono.ttf,FreeSans.ttf,FreeSerif.ttf', input_size=32, lr=0.001, name=None, pretrained=False, push_to_hub=False, resume=None, show_samples=False, test_only=False, train_samples=1, val_samples=1, vocab='french', wb=False, workers=None)
Validation set loaded in 1.729s (126 samples in 126 batches)
Train set loaded in 1.684s (126 samples in 126 batches)
Traceback (most recent call last):-------------------------------------------------------------------------------| 0.00% [0/126 00:00<?]
  File "references/classification/train_tensorflow.py", line 386, in <module>
    main(args)
  File "references/classification/train_tensorflow.py", line 294, in main
    fit_one_epoch(model, train_loader, batch_transforms, optimizer, mb, args.amp)
  File "references/classification/train_tensorflow.py", line 96, in fit_one_epoch
    grads = tape.gradient(train_loss, model.trainable_weights)
  File "/home/nikkokks/.local/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 1063, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/home/nikkokks/.local/lib/python3.8/site-packages/tensorflow/python/eager/imperative_grad.py", line 67, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "/home/nikkokks/.local/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 146, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/home/nikkokks/.local/lib/python3.8/site-packages/tensorflow/python/ops/nn_grad.py", line 582, in _Conv2DGrad
    gen_nn_ops.conv2d_backprop_input(
  File "/home/nikkokks/.local/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1626, in conv2d_backprop_input
    _ops.raise_from_not_ok_status(e, name)
  File "/home/nikkokks/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7262, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__Conv2DBackpropInput_device_/job:localhost/replica:0/task:0/device:CPU:0}} Gradients for grouped convolutions are not supported on CPU. Please file a feature request if you run into this issue. Computed input depth 960 doesn't match filter input depth 1 [Op:Conv2DBackpropInput]
```

Did you have tried to run the code in tensorflow gpu mode ?
I think the problem is due to shapes

when i do 
```
nikkokks@nikokks:~/Desktop/github/doctr$ python3.8
>>> from doctr.models import ocr_predictor
>>> from doctr.io import DocumentFile
>>> USE_TF=1
>>> doc = DocumentFile.from_images('../1.png')
>>> model = ocr_predictor(det_arch='db_resnet50', reco_arch='crnn_mobilenet_v3_small', pretrained=False)
>>> model(doc)
```
it gets
```
2023-06-09 18:51:58.038217: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:417] Loaded runtime CuDNN library: 8.5.0 but source was compiled with: 8.6.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2023-06-09 18:51:58.039157: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at conv_ops.cc:1068 : UNIMPLEMENTED: DNN library is not found.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nikkokks/Desktop/github/doctr/doctr/models/predictor/tensorflow.py", line 89, in __call__
    loc_preds_dict = self.det_predictor(pages, **kwargs)
  File "/home/nikkokks/Desktop/github/doctr/doctr/models/detection/predictor/tensorflow.py", line 46, in __call__
    predicted_batches = [
  File "/home/nikkokks/Desktop/github/doctr/doctr/models/detection/predictor/tensorflow.py", line 47, in <listcomp>
    self.model(batch, return_preds=True, training=False, **kwargs)["preds"] for batch in processed_batches
  File "/home/nikkokks/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/nikkokks/Desktop/github/doctr/doctr/models/detection/differentiable_binarization/tensorflow.py", line 234, in call
    feat_maps = self.feat_extractor(x, **kwargs)
tensorflow.python.framework.errors_impl.UnimplementedError: Exception encountered when calling layer 'conv1_conv' (type Conv2D).

{{function_node __wrapped__Conv2D_device_/job:localhost/replica:0/task:0/device:GPU:0}} DNN library is not found. [Op:Conv2D]

Call arguments received by layer 'conv1_conv' (type Conv2D):
  • inputs=tf.Tensor(shape=(1, 1030, 1030, 3), dtype=float32)
```

As you can see it is due to a line in one of the convolutions in the file doctr/models/classification/mobilenet/tensorflow.py and certainly in the class MobileNetV3

I hope it helps :)

2023-06-09 17:12 UTC, nikokks commented
I am not an expert of this model and I am new to doctr but is the problem here:
```
147        if conf.expanded_channels != conf.input_channels:
148            _layers.extend(conv_sequence(conf.expanded_channels, act_fn, **kernel_size=1,** bn=True, **_kwargs))
```
https://github.com/felixdittrich92/doctr/blob/1bf12a3ec73ddb463420d4243133b2d423a602d3/doctr/models/utils/tensorflow.py#L87

2023-06-09 17:44 UTC, felixdittrich92 commented
> I am not an expert of this model and I am new to doctr but is the problem here:
> 
> ```
> 147        if conf.expanded_channels != conf.input_channels:
> 148            _layers.extend(conv_sequence(conf.expanded_channels, act_fn, kernel_size=1, bn=True, **_kwargs))
> ```
> 
> https://github.com/felixdittrich92/doctr/blob/1bf12a3ec73ddb463420d4243133b2d423a602d3/doctr/models/utils/tensorflow.py#L87

Yeah @nikokks this is not related to the PR so please keep it clean ^^

About the problem: It seems to be a issue with your Tensorflow Installation -> DNN lib cannot be found :)

2023-06-14 20:04 UTC, odulcy-mindee requested changes

2023-06-14 20:04 UTC, odulcy-mindee commented on doctr/models/recognition/zoo.py
I think it would be better to create a wrapper for both tensorflow and pytorch in another file (maybe `doctr.file_utils` or somewhere else) to cast correctly Tensor in `float16/bfloat16` as tensorflow seems to support `bfloat16` as well, what do you think ?

2023-06-14 20:08 UTC, odulcy-mindee commented on doctr/models/recognition/zoo.py
I only saw you previous comment about TF, sorry. But I think we should do this wrapper (only for PyTorch at the moment) in `file_utils` (or somewhere else)

2023-06-20 06:59 UTC, felixdittrich92 commented
Now without the extra kwarg which would only effect PyTorch:
simply do:

```
predictor = (
    ocr_predictor(reco_arch="crnn_mobilenet_v3_small", det_arch="db_mobilenet_v3_large", pretrained=True).cuda().half()
)
```

or

```
predictor = (
    ocr_predictor(reco_arch="crnn_mobilenet_v3_small", det_arch="db_mobilenet_v3_large", pretrained=True).to(device="cuda", dtype=torch.bfloat16)
)
```

2023-06-20 10:27 UTC, odulcy-mindee approved these changes
Definitely better, thanks Felix !

2023-06-20 10:33 UTC, merged