feat: :sparkles: use `tqdm` instead of `fastprogress`
mindee/doctr pull request #1389
Opened 2023-11-22 14:38 UTC by odulcy-mindee

I have not been able to run `train_pytorch.py` script on Colab. An idea is to use `tqdm` instead of `fastprogress`.

Related to https://github.com/mindee/doctr/discussions/1388 and https://github.com/mindee/doctr/discussions/1106

2023-11-22 17:06 UTC, felixdittrich92 requested changes
Thanks @odulcy-mindee lgtm :)
Only one thing if we are onces on it could you extend the progress bar also to each evaluation loop ?

2023-11-23 11:34 UTC, felixT2K commented on references/classification/train_pytorch.py
> +    mb = trange(args.epochs)
Can be removed ?

2023-11-23 11:35 UTC, felixT2K commented on references/classification/train_tensorflow.py
> +    mb = trange(args.epochs)
same and so on :)

2023-11-23 14:14 UTC, odulcy-mindee commented on references/classification/train_pytorch.py
> +    mb = trange(args.epochs)
Yeah, it's not that useful

2023-11-23 14:46 UTC, felixT2K approved these changes
Thanks :)

2023-11-23 14:47 UTC, felixdittrich92 approved these changes

2023-11-23 14:48 UTC, merged