[DRAFT] patch release 0.8.1
mindee/doctr pull request #1490
Opened 2024-02-29 11:52 UTC by felixdittrich92

This PR:

- pypi images fix (hopefully)
- conda fix
- broken pypi changelog url fix
- version 0.8.1

2024-02-29 15:25 UTC, felixdittrich92 commented
@odulcy-mindee 
With the images it should work now tested on https://dillinger.io/

2024-02-29 20:56 UTC, odulcy-mindee requested changes

2024-02-29 20:56 UTC, odulcy-mindee commented on .github/workflows/publish.yml
> +          python -c "import doctr; print(doctr.__version__)"
Did you check locally it worked ?

2024-02-29 20:56 UTC, odulcy-mindee commented on README.md
Can you edit the link in "[We offers Docker container support for easy testing and deployment](https://github.com/mindee/doctr/packages)." to be https://github.com/mindee/doctr/pkgs/container/doctr please ?
Also, there is a typo (We offer without S)

2024-02-29 20:56 UTC, odulcy-mindee commented on README.md
Also, links to LICENSE and CONTRIBUTING are broken on pypi
![image](https://github.com/mindee/doctr/assets/106678676/b13fd300-1c29-49f4-9f87-1b787a552de8)

2024-02-29 21:15 UTC, felixdittrich92 commented on README.md
Sure :)

2024-02-29 21:15 UTC, felixdittrich92 commented on README.md
Ah good catch will fix it 👍

2024-03-01 08:23 UTC, felixdittrich92 commented
@odulcy-mindee Mh there is still a problem with the conda package normally the import test should work i will test a few things before

2024-03-01 09:09 UTC, odulcy-mindee submitted a review, later dismissed
Awesome, thanks !

2024-03-01 15:31 UTC, felixdittrich92 commented
#1493

2024-03-01 15:31 UTC, closed without merging