[TF] First changes on the road to Keras v3
mindee/doctr pull request #1724
Opened 2024-09-13 14:29 UTC by felixdittrich92

This PR:

- is part of a series of PR's
- basic elements to go further forward (only .weights.h5 and .keras (full model) - loading possible in keras v3)
- change to keras imports

- all models works as expected only anything is wrong with the linknet_resnet18 hub uploaded dummy model

Next steps:

- Implement `build` and `get_config` methods for proper loading & saving (serialization)

Any feedback is welcome :hugs: 

NOTE: It's still fully backwards compatible - but marking as breaking change because that will be the last release where you can load `/weights`

2024-09-14 09:59 UTC, felixdittrich92 commented
@odulcy-mindee I see two options:

1. We go step by step with smaller PRs until everything works as expected
2. We iterate on this PR and have one giant PR at the end 😅

What do you prefer ?

2024-09-18 07:30 UTC, felixdittrich92 commented
Next steps:

- try to remove building models first by passing a dummy input -> `build` and `get_config` methods
- test by upgrading to tf >= 2.16 + keras v3 (NOTE: This will be a breaking change -> 1.0.0 - only possible after the next release)
- update training pipeline -> To fix the Dataloader part

2024-09-18 07:34 UTC, felixdittrich92 commented
#1461

2024-09-30 12:36 UTC, odulcy-mindee requested changes

2024-09-30 12:36 UTC, odulcy-mindee commented on references/detection/train_tensorflow.py
> +        _ = model(tf.zeros((1, args.input_size, args.input_size, 3)), training=False)
Don't you need to set `training=True` somewhere after `load_weights` ?

2024-09-30 12:36 UTC, odulcy-mindee commented on tests/tensorflow/test_models_utils_tf.py
> +    url = "https://github.com/mindee/doctr/releases/download/v0.9.0/mobilenet_v3_small-3fcebad7.weights.h5"
```suggestion
    url = "https://doctr-static.mindee.com/models?id=v0.9.0/mobilenet_v3_small-3fcebad7.weights.h5&src=0"
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/recognition/vitstr/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/vitstr_small-d28b8d92.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/vitstr_small-d28b8d92.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/recognition/vitstr/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/vitstr_base-9ad6eb84.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/vitstr_base-9ad6eb84.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/recognition/sar/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/sar_resnet31-5a58806c.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/sar_resnet31-5a58806c.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/recognition/parseq/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/parseq-4152a87e.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/parseq-4152a87e.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/detection/linknet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/linknet_resnet34-9d772be5.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/linknet_resnet34-9d772be5.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/detection/fast/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/fast_tiny-d7379d7b.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/fast_tiny-d7379d7b.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/detection/fast/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/fast_small-44b27eb6.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/fast_small-44b27eb6.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/detection/fast/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/fast_base-f2c6c736.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/fast_base-f2c6c736.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/detection/differentiable_binarization/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/db_resnet50-649fa22b.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/db_resnet50-649fa22b.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/detection/differentiable_binarization/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/db_mobilenet_v3_large-ee2e1dbe.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/db_mobilenet_v3_large-ee2e1dbe.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/vit/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/vit_s-69bc459e.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/vit_s-69bc459e.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/vit/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/vit_b-c64705bd.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/vit_b-c64705bd.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/vgg/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/vgg16_bn_r-b4d69212.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/vgg16_bn_r-b4d69212.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/textnet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/textnet_tiny-a29eeb4a.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/textnet_tiny-a29eeb4a.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/textnet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/textnet_small-1c2df0e3.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/textnet_small-1c2df0e3.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/textnet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/textnet_base-8b4b89bc.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/textnet_base-8b4b89bc.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/resnet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/resnet18-f42d3854.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/resnet18-f42d3854.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/resnet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/resnet31-ab75f78c.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/resnet31-ab75f78c.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/resnet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/resnet34-03967df9.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/resnet34-03967df9.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/resnet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/resnet50-82358f34.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/resnet50-82358f34.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/resnet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/resnet34_wide-b18fdf79.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/resnet34_wide-b18fdf79.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/magc_resnet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/magc_resnet31-16aa7d71.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/magc_resnet31-16aa7d71.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/mobilenet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/mobilenet_v3_large-d857506e.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/mobilenet_v3_large-d857506e.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/mobilenet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/mobilenet_v3_large_r-eef2e3c6.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/mobilenet_v3_large_r-eef2e3c6.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/mobilenet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/mobilenet_v3_small-3fcebad7.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/mobilenet_v3_small-3fcebad7.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/mobilenet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/mobilenet_v3_small_r-dd50218d.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/mobilenet_v3_small_r-dd50218d.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/mobilenet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/mobilenet_v3_small_crop_orientation-ef019b6b.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/mobilenet_v3_small_crop_orientation-ef019b6b.weights.h5&src=0",
```

2024-09-30 12:36 UTC, odulcy-mindee commented on doctr/models/classification/mobilenet/tensorflow.py
> +        "url": "https://github.com/mindee/doctr/releases/download/v0.9.0/mobilenet_v3_small_page_orientation-0071d55d.weights.h5",
```suggestion
        "url": "https://doctr-static.mindee.com/models?id=v0.9.0/mobilenet_v3_small_page_orientation-0071d55d.weights.h5&src=0",
```

2024-10-01 06:12 UTC, felixdittrich92 commented on pyproject.toml
> +    # TODO: This is a temporary fix until we can upgrade to a newer version of tensorflow
Temp pin numpy until we can upgrade tensorflow to fix the issue with `poetry` and the failing API test (Will have effect after merging)

2024-10-01 08:20 UTC, odulcy-mindee approved these changes

2024-10-01 08:34 UTC, merged