Fix resize inconsistency between `detection_predictor()` and `ocr_predictor()` default initialization
mindee/doctr pull request #1765
Opened 2024-10-29 00:28 UTC by cmoscardi

Closes https://github.com/mindee/doctr/issues/1764 -- more details in that issue. Hope this all helps!

2024-10-30 08:21 UTC, felixdittrich92 requested changes
Hi @cmoscardi :wave:,

Thanks for the PR :+1: 

I agree from user view it's cleaner but then we should keep it consistent over all `_predictor` instances and don't miss to update the docstrings :)

I created a branch as reference (feel free to copy from):
https://github.com/felixdittrich92/doctr/commit/c62b851cec2a9f626947b85536536e67fb5de050

2024-11-01 18:51 UTC, felixdittrich92 commented on doctr/models/detection/zoo.py
> +    return _predictor(arch,
@cmoscardi 
arch=arch
pretrained=pretrained

2024-11-01 18:52 UTC, felixdittrich92 commented
@cmoscardi you can apply formatting with `make style` :)

2024-11-01 19:07 UTC, cmoscardi commented
> @cmoscardi you can apply formatting with `make style` :)

Ah thank you! I am in a limited connectivity environment right now and will be able to get the dev dependencies installed in a few hours. I also wanted to run tests before pinging you, thanks for the quick review of this :)

2024-11-01 19:08 UTC, felixdittrich92 commented
> > @cmoscardi you can apply formatting with `make style` :)
> 
> Ah thank you! I am in a limited connectivity environment right now and will be able to get the dev dependencies installed in a few hours. I also wanted to run tests before pinging you, thanks for the quick review of this :)

No stress 😁 👍

2024-11-03 19:51 UTC, cmoscardi commented
OK should be good now!

2024-11-04 06:42 UTC, felixdittrich92 approved these changes
LGTM thanks :+1:

2024-11-04 06:46 UTC, merged