feat: add a drawing_page function in utils & demo
mindee/doctr pull request #320
Opened 2021-06-21 14:19 UTC by charlesmindee

This PR adds a drawing function in utils/visualization.py, which is called in the demo (samples below).

Any feedback is welcome!
![Screenshot_2021-06-21 app · Streamlit(5)](https://user-images.githubusercontent.com/70526046/122777414-4e9c3500-d2ac-11eb-8870-109deb1e28a9.png)
![Screenshot_2021-06-21 app · Streamlit(4)](https://user-images.githubusercontent.com/70526046/122777419-4f34cb80-d2ac-11eb-8dba-d4546071f361.png)
![Screenshot_2021-06-21 app · Streamlit(3)](https://user-images.githubusercontent.com/70526046/122777422-4f34cb80-d2ac-11eb-8601-196770d2b7b8.png)
![Screenshot_2021-06-21 app · Streamlit(2)](https://user-images.githubusercontent.com/70526046/122777425-4fcd6200-d2ac-11eb-8f4f-4057f594dd66.png)
![Screenshot_2021-06-21 app · Streamlit(1)](https://user-images.githubusercontent.com/70526046/122777429-4fcd6200-d2ac-11eb-8bcc-04e66c1ecb59.png)

2021-06-21 14:35 UTC, fg-mindee reviewed
Thanks for the PR!
Two high-level comments: we might need to find a better font size resolution method (on your last examples it looks too small), and regarding the demo, considering the user would have to scroll down, do you think we should display on 2 rows? or keep 1 row and find another layout option?

2021-06-21 15:01 UTC, charlesmindee commented
For the font size, it is very hard to find a global rule because for dense texts it is hard to avoid overlapping between words. I can easily augment the font size but it will be hard to separate words for dense blocks. 
![image](https://user-images.githubusercontent.com/70526046/122783881-40511780-d2b2-11eb-996f-98223e3f6e2d.png)
For the display, I agree but I think displaying the four pics in the same row would be unreadable, do you have any suggestion ?

2021-06-22 16:31 UTC, fg-mindee requested changes
I really don't think it's a good idea to add the font file in the library. Would you mind removing it? If it's for the default font, perhaps we should move everything to OpenCV rather than Pillow :man_shrugging:

2021-06-22 16:31 UTC, fg-mindee commented on doctr/utils/visualization.py
> +                font_size = int(.75 * ((ymax - ymin + np.mean(smoothing)) / 2 - 4))
This needs to be commented as well otherwise flake8 is unhappy :sweat_smile:

2021-06-23 09:08 UTC, charlesmindee commented
This is the rendering after refactoring the writing process (fixed-size font):
![Screenshot_2021-06-23 app · Streamlit(3)](https://user-images.githubusercontent.com/70526046/123069653-44e11180-d413-11eb-847c-daab7d4cfbb4.png)
![Screenshot_2021-06-23 app · Streamlit(2)](https://user-images.githubusercontent.com/70526046/123069655-4579a800-d413-11eb-8184-7bdc398e0a82.png)
![Screenshot_2021-06-23 app · Streamlit(1)](https://user-images.githubusercontent.com/70526046/123069659-46aad500-d413-11eb-8af3-567857ffbf46.png)

2021-06-23 10:02 UTC, fg-mindee approved these changes
Thanks for the edits!

2021-06-23 10:14 UTC, merged