fix: :bug: fix sar saved model export
mindee/doctr pull request #635
Opened 2021-11-18 10:20 UTC by khalidMindee

This PR solves #602 for SAR recognition models to allow export as a saved model.

2021-11-21 19:26 UTC, fg-mindee requested changes
Thanks for the PR! I added some comments, let's avoid breaking changes in this PR if possible :pray:

2021-11-21 19:26 UTC, fg-mindee commented on doctr/models/recognition/sar/tensorflow.py
> +
This needs to stay, was it blocking the savedmodel export?

2021-11-21 19:26 UTC, fg-mindee commented on doctr/models/recognition/sar/tensorflow.py
> +                #'Need to provide labels during training for teacher forcing'
no need to duplicate comment

2021-11-21 19:26 UTC, fg-mindee commented on doctr/models/recognition/sar/tensorflow.py
> +            if kwargs.get('training') and gt is not None:
can be reverted since we already ensure that the gt is provided in training mode above

2021-11-21 19:26 UTC, fg-mindee commented on doctr/models/recognition/sar/tensorflow.py
> +        }
We can't change the output signature of the call method in this PR or we'll break the high-level API

2022-04-08 18:51 UTC, fharper commented
@khalidMindee is this PR still good? If yes, can you review FG's comments, modify in consequences so we can potentially merge it please?

2022-06-23 10:16 UTC, khalidMindee commented
Ah great @felixdittrich92 that's fine for me to close the PR .

2022-06-23 14:27 UTC, closed without merging