[refactor] unify the boxes in relative coordinates
mindee/doctr pull request #702
Opened 2021-12-13 13:14 UTC by felixdittrich92

This PR unified the boxes for each dataset which holds boxes

motivation:
we need a clean output format to work further with these

Any feedback and suggestions are very welcome :hugs:

2021-12-17 19:13 UTC, fg-mindee reviewed
Thanks for the PR! I added a few comments but the general discussion is about changing the target of text detection :thinking: 

I'm starting to think that if we go this way, we should switch to object detection targets (having labels = 0 = "text" class). Anyway, there are conflicts with the main branch :sweat_smile:

2021-12-17 19:13 UTC, fg-mindee commented on doctr/datasets/cord.py
> +                dict(boxes=np.asarray(box_targets, dtype=np_dtype), labels=text_targets)
careful here, we still need the clipping

2021-12-17 19:13 UTC, fg-mindee commented on doctr/datasets/datasets/base.py
> +                not np.all((target['boxes'] <= 1) & (target['boxes'] >= 0)):
It would be better to have a dynamic flag: 
```python
if self.convert_to_relative:
```
that would be set in the constructor

2021-12-17 19:13 UTC, fg-mindee commented on tests/pytorch/test_datasets_pt.py
> +    assert isinstance(target['labels'], list) or isinstance(
Lazy can be cleaner sometimes :)
```python
assert isinstance(target['labels'], (list, tuple, np.ndarray))
```

2021-12-17 19:13 UTC, fg-mindee commented on tests/tensorflow/test_datasets_tf.py
> +        target['labels'], tuple) or isinstance(target['labels'], np.ndarray)
same here

2021-12-18 21:57 UTC, felixdittrich92 commented
@fg-mindee 
Lets discuss this on monday via Slack in a short way :)
Fine with your requested changes :+1:  .. but we need a check in base.py for coordinates :hugs:

2021-12-20 12:53 UTC, fg-mindee requested changes
Some extra suggestions in the comments :)

2021-12-20 12:53 UTC, fg-mindee commented on doctr/datasets/datasets/base.py
> +        if isinstance(target, dict) and 'boxes' in target.keys() and self.convert_to_relative:
No need to check for something else than `self.convert_to_relative` considering we're unifying the target format

2021-12-20 12:53 UTC, fg-mindee commented on doctr/datasets/datasets/base.py
> +            if not np.all((target['boxes'][:, :4] <= 1) & (target['boxes'][:, :4] >= 0)):
Same here, this can removed, we'll send to correct flag to specify whether the data need conversion in getitem directly.

2021-12-20 12:53 UTC, fg-mindee commented on doctr/datasets/datasets/base.py
> +        convert_to_relative: bool = True,
We need to add kwargs in `_VisionDataset` constructor, that are then passed to this constructor

2021-12-20 12:53 UTC, fg-mindee commented on doctr/datasets/cord.py
> +        np_dtype = np.float32
On the constructor call line 50, we need to specify the value for `convert_to_relative`

2021-12-20 12:53 UTC, fg-mindee commented on doctr/datasets/funsd.py
> +        np_dtype = np.float32
Same in the constructor of this one

2021-12-20 12:53 UTC, fg-mindee commented on tests/pytorch/test_datasets_pt.py
> +    assert isinstance(target['boxes'], np.ndarray) and target['boxes'].dtype == np.float32
Before this line, we need a `assert isinstance(target, dict)`

2021-12-20 12:53 UTC, fg-mindee commented on tests/tensorflow/test_datasets_tf.py
> +    assert isinstance(target['boxes'], np.ndarray) and target['boxes'].dtype == np.float32
same here

2021-12-21 19:01 UTC, fg-mindee reviewed
Thanks Felix! cf my comment, let's pause this PR while I figure out how to handle this

2021-12-21 19:19 UTC, felixdittrich92 commented on tests/conftest.py
> +        "wordBB": [np.random.uniform(low=100., high=600., size=(2, 4, 2)) for _ in range(3)],
@fg-mindee 
Yes i have checked the set again which uses float values around ~100.0 up to ~600.0 and i have faiced that the shape is wrong after testing also rotated boxes if have found this typo last dim 3 -> 2

2021-12-21 19:30 UTC, felixdittrich92 commented on doctr/datasets/datasets/base.py
> +
Ok but i would really suggest to tackle this before the next release .. to harmonize the dataset and also coresponding test part .. overall the structure (datasets) feels a bit caotical so at starting point the time to fix it 👍 😃

2021-12-31 18:17 UTC, fg-mindee commented
Closed in favour of #775

2021-12-31 18:17 UTC, closed without merging