feat: add aspect ratio for ocr predictor
mindee/doctr pull request #835
Opened 2022-02-25 11:00 UTC by charlesmindee

This PR adds the option to preserve aspect ratio of the pages in the whole OCRPredictor pipeline, which leads to much better results on the detection task. 
Any feedback is welcome!

2022-03-07 11:34 UTC, fg-mindee requested changes
Thanks for the PR!
I added a few comments, could you confirm whether this improves perf with the existing checkpoints? (it isn't specified in the PR details, so I prefer to make sure we use everything)

If that improves for existing checkpoints (trained with images that were stretched, that should strongly indicate that we should update our resizing strategy for detection training asap :))

2022-03-07 11:34 UTC, fg-mindee commented on doctr/models/predictor/base.py
> +        symmetric_pad: bool = True,
The docstring needs to be updated :)

2022-03-07 17:40 UTC, charlesmindee commented
Yes @fg-mindee it doesn't hurt performances for now, and I will retrain all detection models preserving the aspect ratio to have a coherent pipeline, because it is way better not to deform writtings on documents for the model convergence!

2022-03-07 17:50 UTC, fg-mindee submitted a review, later dismissed
Nice!

2022-03-09 13:33 UTC, fg-mindee approved these changes
Thanks!

2022-03-09 13:42 UTC, merged