[WIP][PoC] Improve dataset usage for recognition task
mindee/doctr pull request #867
Opened 2022-03-23 09:58 UTC by felixdittrich92

This PR is handled as Proof of Concept for further discussions to enable the ability to use existing datasets also for recognition task ( main goal: benchmarks ).
It's easier to show the idea directly in code instead of opening a discussion.

Things to investigate if the concept should be fine:
- Synthtext cropping is to slow (multiprocessing or maybe another way to prefer ?)
- maybe revert the hard set use polygon that the user can decide

@fg-mindee 
No worry we can split this later in parts (maybe geometry, torch, tf) for review if you want :sweat_smile: 

Issue: 
#855  First task of this

Any feedback is very welcome :+1: 
@charlesmindee @SiddhantBahuguna @fg-mindee

2022-03-30 09:52 UTC, felixdittrich92 commented
@fg-mindee 
I saw we have already `extract_crops` `extract_rcrops` in `models/_utils.py ` can we maybe move this to geometry ?

2022-04-05 21:19 UTC, felixdittrich92 commented
@frgfm
Same here any feedback ? 😄

2022-04-06 17:32 UTC, frgfm commented
Hey there 🙂

So I had thought about this a few months back. To make sure we are all on the same page, the goal is to:
- take OCR annotated datasets
- make a text recognition dataset out of it 

Correct?

If so, two major options arise:
- doing this dynamically (at it getitem)
- doing this statically in the constructor


If this is for training, I'd argue the second option is the one for a few reasons :
- latency
- memory consumption (opening an image 100 times as big to crop it, in a number of samples that isn't necessarily the batch size comes with heavy consequences)

So perhaps this could be done in a temporary or cache folder 🤷‍♂️

What do you think?

2022-04-06 19:50 UTC, felixdittrich92 commented
@frgfm 
Yes you are right that's the goal :)
I have had this ways also in mind so currently i have implemented the 'constructor' option (which works really good) with one problem .... SynthText 😓 it is much to slow and needs a lot of memory (really much ~30gb ram) ...but thanks for your opinon now i can iterate on this and find a way to make it better performing 👍 
I was also on track to think about saving for faster reload but it's no option it would waste a lot of the users space
One last thing for the moment are you fine if i move extract_rcrops / extract_crops to geometry otherwise we will have duplicated stuff !? :)

2022-04-07 20:12 UTC, felixdittrich92 commented
I think it's mostly done i will split it into 2 PRs for easier reviews :+1:

2022-04-08 19:00 UTC, fharper requested changes
Can you fix the issues found by Codacy & CodeFactor please?

2022-04-10 08:57 UTC, felixdittrich92 commented
@fharper that' s only a PoC PR will be split into 2 PRs for review 👍 
Part 1: #889

2022-04-27 15:28 UTC, closed without merging