Update `io/pdf.py` to new pypdfium2 API
mindee/doctr pull request #944
Opened 2022-06-08 17:48 UTC by mara004

This patch would make doctr compatible with pypdfium2 >= 2.0.0, which will be released soon.
Now that pypdfium2 supports extracting text and locating images, it would also be possible to add back some features that were removed with https://github.com/mindee/doctr/pull/829.

2022-06-08 17:51 UTC, mara004 commented
CI currently fails because of the >= 2.0.0 requirement, considering that this version is not actually released yet.

2022-06-08 19:38 UTC, felixdittrich92 commented
@mara004 Thanks a lot for this update :+1:

2022-06-09 12:54 UTC, felixdittrich92 commented
@mara004 thanks only a few minor things left :+1:

2022-06-09 12:55 UTC, mara004 commented on doctr/io/pdf.py
> +    pdf = pdfium.PdfDocument(file, password=password)
Sorry, that's not available yet. PdfDocument currently doesn't implement `__enter__()` and `__exit__()`.

2022-06-09 13:07 UTC, felixdittrich92 requested changes

2022-06-09 13:57 UTC, felixdittrich92 commented on doctr/io/pdf.py
> +    ) -> List[np.ndarray]:
```
def read_pdf(
    file: AbstractFile, 
    scale: float = 2, 
    password: Optional[str] = None, 
    **kwargs: Any,
) -> List[np.ndarray]:
```
you can check the style also with `flake8 .` in the project directory :+1:

2022-06-09 15:52 UTC, felixdittrich92 approved these changes
Thanks a lot :)

2022-06-09 15:54 UTC, merged

2022-06-09 16:38 UTC, mara004 commented
Thank you for reviewing/merging!

2022-06-23 15:07 UTC, frgfm reviewed
Thanks a lot @mara004 :)

Just a few comments & questions out of curiosity!

2022-06-23 15:23 UTC, mara004 commented on doctr/io/pdf.py
> +    password: Optional[str] = None,
I agree the term "Optional" is confusing for required parameters, but as `password` is actually optional, I wouldn't worry about that here. What about keeping it as-is for now and switching to `str | None` once you require Python >=3.10 ?

2022-06-23 15:27 UTC, mara004 commented on doctr/io/pdf.py
> +    pdf = pdfium.PdfDocument(file, password=password)
As you can see in https://github.com/mindee/doctr/pull/953, `PdfDocument` now provides the context manager API, so you can use any instance of this class in a `with` block, meaning that `.close()` will be called automatically once the context manager exits. Does this answer your question?